"""add teacher_assignment

Revision ID: 0c768ec61eee
Revises: 73cab240f4b7
Create Date: 2026-03-19 22:04:49.198845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c768ec61eee'
down_revision: Union[str, None] = '73cab240f4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_teacher_assignments_assignment_id_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_teacher_assignments_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id', 'teacher_id', name=op.f('pk_teacher_assignments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_assignments')
    # ### end Alembic commands ###
