"""create course-classes table

Revision ID: 18c4f00d118d
Revises: e6fdd6a1c137
Create Date: 2026-03-20 11:39:14.703819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c4f00d118d'
down_revision: Union[str, None] = 'e6fdd6a1c137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_classes',
    sa.Column('class_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('fk_course_classes_course_id_courses')),
    sa.PrimaryKeyConstraint('class_id', name=op.f('pk_course_classes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_classes')
    # ### end Alembic commands ###
