"""fix student_submission table

Revision ID: 1afa713afcef
Revises: e4f805fe1b0f
Create Date: 2026-03-26 16:55:45.031736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afa713afcef'
down_revision: Union[str, None] = 'e4f805fe1b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_submissions', sa.Column('analysis_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_submissions', 'analysis_report')
    # ### end Alembic commands ###
