"""create student table

Revision ID: 32fd3e579a44
Revises: 516d039888e3
Create Date: 2026-03-19 16:47:08.209012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fd3e579a44'
down_revision: Union[str, None] = '516d039888e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], name=op.f('fk_students_student_id_user')),
    sa.PrimaryKeyConstraint('student_id', name=op.f('pk_students')),
    sa.UniqueConstraint('email', name=op.f('uq_students_email')),
    sa.UniqueConstraint('student_no', name=op.f('uq_students_student_no'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
