"""create teacher table

Revision ID: 516d039888e3
Revises: f64839fb54da
Create Date: 2026-03-19 16:03:58.324312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516d039888e3'
down_revision: Union[str, None] = 'f64839fb54da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.user_id'], name=op.f('fk_teachers_teacher_id_user')),
    sa.PrimaryKeyConstraint('teacher_id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('email', name=op.f('uq_teachers_email')),
    sa.UniqueConstraint('teacher_no', name=op.f('uq_teachers_teacher_no'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    # ### end Alembic commands ###
