"""update assignment

Revision ID: 54af6245d06a
Revises: 0c768ec61eee
Create Date: 2026-03-19 22:16:43.536591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54af6245d06a'
down_revision: Union[str, None] = '0c768ec61eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_assignments_user_id_user'), 'assignments', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_assignments_user_id_user'), 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'user_id')
    # ### end Alembic commands ###
