"""create temp_question table

Revision ID: 5c3acbf85e19
Revises: f2dc30a4e405
Create Date: 2026-03-19 12:54:46.116549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3acbf85e19'
down_revision: Union[str, None] = 'f2dc30a4e405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('q_type', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options_data', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_question'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_question')
    # ### end Alembic commands ###
