"""add q_count to assignments

Revision ID: 73cab240f4b7
Revises: 582236cc5c05
Create Date: 2026-03-19 21:02:08.177387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cab240f4b7'
down_revision: Union[str, None] = '582236cc5c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('q_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'q_count')
    # ### end Alembic commands ###
