"""create student_submission table

Revision ID: baabefa9eed6
Revises: 6b138cb35a7a
Create Date: 2026-03-21 15:45:50.914541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baabefa9eed6'
down_revision: Union[str, None] = '6b138cb35a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submit_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('answer_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('is_manual_submit', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['class_assignment_id'], ['class_assignments.id'], name=op.f('fk_student_submissions_class_assignment_id_class_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_student_submissions_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_submissions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_submissions')
    # ### end Alembic commands ###
