"""update question table

Revision ID: bb10ae286d44
Revises: b591d345fa40
Create Date: 2026-03-18 23:01:45.140191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb10ae286d44'
down_revision: Union[str, None] = 'b591d345fa40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'create_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('create_time', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
