"""fix student_submission table

Revision ID: e4f805fe1b0f
Revises: baabefa9eed6
Create Date: 2026-03-23 20:26:19.908860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4f805fe1b0f'
down_revision: Union[str, None] = 'baabefa9eed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_submissions', sa.Column('scores', sa.JSON(), nullable=False))
    op.add_column('student_submissions', sa.Column('total_score', sa.Integer(), nullable=False))
    op.drop_column('student_submissions', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_submissions', sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('student_submissions', 'total_score')
    op.drop_column('student_submissions', 'scores')
    # ### end Alembic commands ###
