"""create class_student table

Revision ID: f13673f8bc78
Revises: 87dcc1f2388c
Create Date: 2026-03-20 15:09:28.143406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13673f8bc78'
down_revision: Union[str, None] = '87dcc1f2388c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_students',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['course_classes.class_id'], name=op.f('fk_class_students_class_id_course_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('fk_class_students_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_class_students_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'student_id', name=op.f('pk_class_students')),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_course_limit')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_students')
    # ### end Alembic commands ###
